---
title: "Enriquecimiento Red Drosophila"
author: "Diego Mañanes"
date: "29/4/2020"
output: html_document
---

```{r setup, include=FALSE}

outputPath <- "/home/diego/Documentos/proyectos_master/proyectos_redes/trabajos_redes/Práctica_Final/datos"

if (! dir.exists(file.path(outputPath, "Figuras"))) {
  dir.create(file.path(outputPath, "Figuras"), showWarnings = F)
}


knitr::opts_chunk$set(
    fig.align = "center",
    fig.path = file.path(outputPath, "Figuras/"),
    fig.pos = "H",
    message = FALSE,
    warning = FALSE,
    comment = NA,
    dev = c("jpeg"),
    dpi = 300
)



## packages used
library(clusterProfiler)
library(ReactomePA)
library(KEGGprofile)
library(org.Dm.eg.db)

library(ChIPpeakAnno)
library(annotatr)
library(ChIPseeker)


```


```{r}

genesCommunities <- read.csv(file.path(outputPath, "max_tabla_comunidades.csv"))

listCommunities <- split(genesCommunities, genesCommunities$community)

filterLen <-sapply(listCommunities, function(x) {ifelse(length(x$node) >= 200, 
                                                        return(x), return(NULL))})

mappingGenes <- as.data.frame(org.Dm.egALIAS2EG)
matching <- match(filterLen$`0`$node, mappingGenes$alias_symbol)

filterLen_mapped <- sapply(filterLen, function(x) {
  if (! is.null(x[[1]])){
    matching <- match(x$node, mappingGenes$alias_symbol)
    return(mappingGenes$gene_id[matching])
  }
})

filt_null <- sapply(filterLen_mapped, function(x) ! is.null(x))
filterLen_mapped <- filterLen_mapped[filt_null]

```

```{r}

n <- 1
ggo1 <- list()
  
for (i in filterLen_mapped) {
  x <- sapply(c("MF", "CC", "BP"), function(term) {
                    enrichGO(unique(i), org.Dm.eg.db,
                    ont = term, qvalueCutoff = 0.05,
                    readable = TRUE)})

  ggo1[[names(filterLen_mapped)[n]]] <- x
  n <- n + 1              
  }

```



```{r plotGoAllGenes}
n <- 1
for (x in ggo1) {
  print(barplot(x$MF, showCategory = 10, font.size = 9, 
                title = paste("Función Molecular. Comunidad de orden", 
                              length(filterLen_mapped[[n]]))))
  print(barplot(x$BP, showCategory = 10, font.size = 9, 
                title = paste("Proceso Biológico. Comunidad de orden", 
                              length(filterLen_mapped[[n]]))))
  print(barplot(x$CC, showCategory = 10, font.size = 9, 
                title = paste("Componente Celular. Comunidad de orden", 
                              length(filterLen_mapped[[n]]))))
  n <- n + 1
}
```


```{r}

n <- 1
reactome <- list()
  
for (i in filterLen_mapped) {
  x <- enrichPathway(na.omit(as.integer(i)), organism = "fly")

  reactome[[names(filterLen_mapped)[n]]] <- x
  n <- n + 1              
}

```

```{r reactomePathways}

n <- 1
for (x in reactome) {
  print(barplot(x, showCategory = 5, font.size = 10, 
                title = paste("Función Molecular. Comunidad de orden", 
                              length(filterLen_mapped[[n]]))))
  
  n <- n + 1
}

```




```{r eval=FALSE, include=FALSE}
kegg1 <- enrichKEGG(gene = listCommunities[[1]]$node,
                    organism = "dme")

kpho_KEGGresult <- find_enriched_pathway(listCommunities[[1]]$node, 
                                        species = 'dme')

```

